### PR TITLE
Polski

### PR DESCRIPTION
**Pull request by Piter432**
- Added VID_PLR_HFR label

### CODE REVIEW

**Comment by ParticleCore** [comment]
Thanks for the update, but can't it be closer to the original label? The link for the feature description already takes care of the explanation, the feature itself needs to be short and straight like the one in English is. Is it not possible to directly translate `Disable HFR (60fps)` like `Wyłącz HFR (60fps)`?

**Comment by Piter432** [comment]
Can be something like [this](https://github.com/Piter432/Particle/commit/bcb1a4cbe3bd7380db1ecf15cbdbb4114245896d)?

**Comment by ParticleCore** [comment]
Not really because it is not forcing 30fps, it is disabling High Frame Rates which can be anything above 30fps and up to 60fps, leaving intact every other stream that is 30fps and lower. It doesn't need to translate HFR since it is a nomenclature, only the essence of the feature so that any user can look at it and understand easily what it will do once it is activated.

**Comment by Piter432** [comment]
Well, I take care about my language and that's why I try to translate almost all to my language as accurate as I can (I hate fashion in my country, where many Poles in many Polish sentences uses English words by force or slightly translate them to Polish [Ehh, can't find a proper example :/]), but okay, I will do as I wrote :)

**Comment by ParticleCore** [comment]
Perfect! I've added the new label.

Sorry for the trouble, but if it isn't done the right way it can generate confusion for the users. And of course, thanks again for your help!

**Pull request closed without merging**
