### PR TITLE
Русский

### PR DESCRIPTION
**Pull request by Habetdin**
Russian localization

### CODE REVIEW

**Comment by ParticleCore** [comment]
Thank you for your contribution but it is incomplete, the following labels are missing:

````json

    "CNSL_SKMP"             : "Seek map",
    "CNSL_SKMP_OFF"         : "No thumbs found",
    "CNSL_SKMP_SMAL"        : "SMALL",
    "CNSL_SKMP_MED"         : "MEDIUM",
    "CNSL_SKMP_LRGE"        : "LARGE",
````

If you could include them I will gladly add it to the locale distribution channel.

**Comment by Habetdin** [comment]
Could you show the code where it will be used? I'm bit confused of context that will change the meaning of these lables and didn't found CNSL_SKMP in script files to look it.

**Comment by ParticleCore** [comment]
I forgot that this was a feature I removed, what I have to do is remove the same labels from the other locales. I will work on this right now, there's nothing else you have to do.

**Comment by Habetdin** [comment]
Okay, no problem :)
Also, the CNSL_CNSL string is not used in code too.

**Comment by ParticleCore** [comment]
You are correct, it was previously the name of the console area, eventually it was changed to "Advanced options". I will also remove that label since it is unnecessary.

I have [added the file](https://github.com/ParticleCore/Particle/blob/master/Locale/ru_RU.json) to the locale directory, it should load automatically in the next 24h or less for users that are using YouTube with Russian language selected. Thank you for contributing with this translation and your tips!

**Pull request closed without merging**
