### PR TITLE
中文 (简体)

### PR DESCRIPTION
**Pull request by fireattack**
Changed wrong translation  (reverse=倒序, not 后退) and improved the phrases for others.

### CODE REVIEW

**Comment by ParticleCore** [comment]
Thanks for this! But can you follow the locale guide? https://github.com/ParticleCore/Particle/wiki/Translation-template#merge-request

Basically all that has to be done is change the commit title from `Update zh_CN.json` to `中文 (简体)`

The easiest way is to delete your commit and repeat your changes, this time with the correct commit title.

**Comment by fireattack** [comment]
What about this way?

**Comment by ParticleCore** [comment]
Let's see if it works this way

**Comment by ParticleCore** [comment]
It didn't work, changing the title without issuing a new commit doesn't really change the title when I merge it afterwards. It's not a problem, next time we already know. Thanks for the corrections and updates!

**Pull request merged**
