### PR TITLE
Nederlands

### PR DESCRIPTION
**Pull request by Nhoise**
Created file for Dutch locale.

First time doing a PR so I hope everything's ok.

### CODE REVIEW

**Comment by ParticleCore** [comment]
Everything looks perfect except for the commit title, change `Update nl_NL.json` to `Nederlands` and I'll merge it!

**Comment by ParticleCore** [comment]
Perhaps it would be best if you delete the locale and create it again like you did before, this time with the right commit title.

**Comment by Nhoise** [comment]
Yeah, I'll do that.   
It's weird because here it's showing the changed commit title but in my fork it isn't.
But that might be because I have no idea what I'm doing.

**Comment by ParticleCore** [comment]
I noticed it, it's strange that the commit was leading to an empty file instead of the locale. Now everything looks right!

**Comment by ParticleCore** [comment]
Thanks for the contribution! It will be available to the users with Nederlands language selected on YouTube once YT+ checks for its availability.

**Comment by Nhoise** [comment]
You're welcome. I'll check again to see if everything looks correct when it's available.

**Pull request merged**
